### ISSUE TITLE
Package cl is deprecated

### ISSUE THREAD

**Issue by KJ2ME** [magnars/dash.el#385] opened 2021-08-30 20:11 UTC
Hi when starts emacs I have that warning.

Checking the code, I found this on "dash.el":

```(eval-when-compile
  (unless (fboundp 'gv-define-setter)
    (require 'cl)))
```

**Comment by basil-conto** [comment] 2021-08-31 09:01
> Checking the code, I found this on "dash.el":

That code only loads `cl` at runtime in old versions of Emacs 24.  What is your precise `M-x emacs-version RET`?

Are you sure the warning you're seeing is not from some other package, or your own config?  You can verify this by starting Emacs as `emacs -Q` and then loading only `dash.elc`.

In any case, this sounds like a duplicate of #335, #337, and #378, so I'm closing this until further notice.  If you discover an issue that hasn't already been covered, we can always reopen.  Thanks.

**Closed by basil-conto** 2021-08-31 09:01 UTC
