### ISSUE TITLE
-let without the repetition?

### ISSUE THREAD

**Issue by fommil** [magnars/dash.el#183] opened 2016-05-25 20:38 UTC
I just discovered `-let` and I'm in love :heart_eyes: 

To make it even better for my typical usecase

```elisp
(-let [(&plist :foo foo :bar bar) (list :baz 3 :foo 1 :qux 4 :bar 2)] (list foo bar))
```

would it be possible to drop the repetition of `:foo foo` and write something like this proposed syntax?

```elisp
(-let [(&keys :foo :bar) (list :baz 3 :foo 1 :qux 4 :bar 2)] (list foo bar))
```

**Comment by Fuco1** [comment] 2016-05-25 21:02
This is a duplicate of #111.  There are some questions, you are very welcome to answer or provide feedback.

This is still on my todo list, just with lower priority now.  I'll close this, but as I said please post any ideas/feedback into the other issue.

**Closed by Fuco1** 2016-05-25 21:02 UTC

**Comment by fommil** [comment] 2016-05-25 21:03
sorry, I don't know how I missed the original! I'll subscribe, thanks :smile:

**Comment by Fuco1** [comment] 2018-07-11 11:41
There is now an experimental branch with this feature, check #111
